services:
  postgres:
    image: postgres:17-alpine
    container_name: elite-dev-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: event_platform
      POSTGRES_USER: postgres_usr
      POSTGRES_PASSWORD: postgres_pwd

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres_usr -d event_platform"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: