"""Make external catalog id nullable

Revision ID: dcc098d94d8a
Revises: e94de7d06ff7
Create Date: 2026-08-28 10:24:28.748886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcc098d94d8a'
down_revision: Union[str, Sequence[str], None] = 'e94de7d06ff7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'external_catalog_item_id',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'external_catalog_item_id',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    # ### end Alembic commands ###
