"""add catalogue item images

Revision ID: e94de7d06ff7
Revises: dcee2126d687
Create Date: 2026-08-28 09:05:18.996782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e94de7d06ff7'
down_revision: Union[str, Sequence[str], None] = 'dcee2126d687'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_catalog_item_images',
    sa.Column('catalog_item_id', sa.String(length=60), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('ratio', sa.String(length=20), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('fallback', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_item_id'], ['external_catalog_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_catalog_item_images_catalog_item_id'), 'external_catalog_item_images', ['catalog_item_id'], unique=False)
    op.create_index(op.f('ix_external_catalog_item_images_id'), 'external_catalog_item_images', ['id'], unique=False)
    op.drop_column('external_catalog_items', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('external_catalog_items', sa.Column('image_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_external_catalog_item_images_id'), table_name='external_catalog_item_images')
    op.drop_index(op.f('ix_external_catalog_item_images_catalog_item_id'), table_name='external_catalog_item_images')
    op.drop_table('external_catalog_item_images')
    # ### end Alembic commands ###
